COMPANY_CONVERSATION_TABLE = """create table {company_id}.conversations (
  conversation_id uuid not null default gen_random_uuid (),
  conversation_name text not null,
  ai_reply boolean not null default true,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone null default now(),
  source text not null,
  phone_number text null,
  instance_name text null,
  constraint conversations_pkey primary key (conversation_id)
) TABLESPACE pg_default;"""

COMPANY_MESSAGE_TABLE = """create table {company_id}.messages (
  message_id bigint generated by default as identity not null,
  conversation_id uuid not null,
  sender_type text not null,
  sender_email text null,
  content text not null,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  extra json null,
  constraint messages_pkey primary key (message_id),
  constraint messages_conversation_id_fkey foreign KEY (conversation_id) references {company_id}.conversations (conversation_id),
  constraint messages_sender_type_check check (
    (
      sender_type = any (
        array['customer'::text, 'bot'::text, 'agent'::text]
      )
    )
  )
) TABLESPACE pg_default;
"""

COMPANY_IMAGE_TABLE = """create table {company_id}.images (
  id uuid not null default gen_random_uuid (),
  file_name text not null,
  file_type text not null,
  file_hash text not null,
  full_path text not null,
  status text not null,
  extra json null,
  match_field text not null,
  created_at timestamp with time zone not null default now(),
  constraint images_pkey primary key (id)
) TABLESPACE pg_default;"""

COMPANY_EXTRA_TABLE = """create table {company_id}.documents (
  id uuid not null default gen_random_uuid (),
  file_name text not null,
  file_type text not null,
  file_hash text not null,
  full_path text not null,
  status text not null,
  extra json null,
  match_field text not null,
  created_at timestamp with time zone not null default now(),
  constraint documents_pkey primary key (id)
) TABLESPACE pg_default;"""

COMPANY_KNOWLEDGE_TABLE = """create table {company_id}.knowledges (
  id uuid not null default gen_random_uuid (),
  file_name text not null,
  file_type text not null,
  file_hash text not null,
  full_path text not null,
  status text not null,
  primary_column text not null,
  extra json null,
  created_at timestamp with time zone not null default now(),
  constraint knowledges_pkey primary key (id)
) TABLESPACE pg_default;
"""

COMPANY_WORKFLOW_TABLE = """create table {company_id}.workflows (
  id uuid not null default gen_random_uuid (),
  name text not null,
  nodes json not null,
  edges json not null,
  status text not null,
  enable_workflow boolean not null,
  except_case text not null,
  extra json null,
  created_at timestamp with time zone not null default now(),
  constraint workflows_pkey primary key (id)
) TABLESPACE pg_default;
"""