# public.companies schema
PUBLIC_COMPANIES_TABLE = """create table if not exists public.companies (
  id uuid not null default gen_random_uuid (),
  name text not null,
  description text null,
  schema_name text not null default ''::text,
  active boolean not null default false,
  created_at timestamp with time zone not null default now(),
  constraint companies_pkey primary key (id),
  constraint companies_schema_name_key unique (schema_name)
) TABLESPACE pg_default;"""

# public.roles schema
PUBLIC_ROLES_TABLE = """create table if not exists public.roles (
  id uuid not null default gen_random_uuid (),
  name text not null,
  permissions json not null,
  created_at timestamp with time zone not null default now(),
  constraint roles_pkey primary key (id)
) TABLESPACE pg_default;"""

# public.users schema
PUBLIC_USERS_TABLE = """create table if not exists public.users (
  id uuid not null default gen_random_uuid (),
  name text not null,
  password text not null,
  email text not null,
  company_id uuid not null,
  invited_by uuid null,
  role text not null,
  created_at timestamp with time zone not null default now(),
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email),
  constraint users_company_id_fkey foreign KEY (company_id) references companies (id)
) TABLESPACE pg_default;"""

# public.invitations schema
PUBLIC_INVITATIONS_TABLE = """create table if not exists public.invitations (
  id uuid not null default gen_random_uuid (),
  company_id uuid not null,
  invited_email text not null,
  invited_by uuid not null,
  token_hash text not null,
  role uuid not null,
  status text not null,
  created_at timestamp with time zone not null default now(),
  constraint invitations_pkey primary key (id),
  constraint invitations_company_id_fkey foreign KEY (company_id) references companies (id),
  constraint invitations_invited_by_fkey foreign KEY (invited_by) references users (id),
  constraint invitations_role_fkey foreign KEY (role) references roles (id)
) TABLESPACE pg_default;"""

COMPNY_SCHEMA_CREATE = """create schema {company_id};"""

COMPANY_CONVERSATION_TABLE = """create table {company_id}.conversations (
  conversation_id uuid not null default gen_random_uuid (),
  conversation_name text not null,
  ai_reply boolean not null default true,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone null default now(),
  source text not null,
  phone_number text null,
  instance_name text null,
  constraint conversations_pkey primary key (conversation_id)
) TABLESPACE pg_default;"""

COMPANY_MESSAGE_TABLE = """create table {company_id}.messages (
  message_id bigint generated by default as identity not null,
  conversation_id uuid not null,
  sender_type text not null,
  sender_email text null,
  content text not null,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  constraint messages_pkey primary key (message_id),
  constraint messages_conversation_id_fkey foreign KEY (conversation_id) references {company_id}.conversations (conversation_id),
  constraint messages_sender_type_check check (
    (
      sender_type = any (
        array['customer'::text, 'bot'::text, 'agent'::text]
      )
    )
  )
) TABLESPACE pg_default;
"""

ADD_CONVERSATION_INTO_TABLE =  """INSERT INTO {company_id}.conversations (conversation_name, source, phone_number, instance_name) VALUES (\'{conversation_name}\', \'{source}\', \'{phone_number}\', \'{instance_name}\')"""

GET_ALL_CONVERSATIONS_QUERY = """SELECT * FROM {company_id}.conversations;"""

GET_CONVERSATION_WITH_ID_QUERY = """SELECT * FROM {company_id}.conversations WHERE conversation_id = \'{conversation_id}\';"""

GET_CONVERSATION_WITH_PHONE_INTEGRATION_QUERY = """SELECT * FROM {company_id}.conversations WHERE phone_number = \'{phone_number}\' AND instance_name = \'{instance_name}\';"""

GET_MESSAGES_BY_CONVERSATION_ID_QUERY = """SELECT * FROM {company_id}.messages WHERE conversation_id = \'{conversation_id}\';"""

UPDATE_MESSAGE_BY_ID_QUERY = """INSERT INTO {company_id}.messages (conversation_id, sender_type, sender_email, content) VALUES (\'{conversation_id}\', \'{sender_type}\', \'{sender_email}\', \'{content}\')"""

GET_UNANSWERED_CONVERSATIONS_QUERY = """SELECT m.message_id, c.conversation_id, c.conversation_name, c.source, m.sender_type, m.sender_email, m.content, m.created_at
FROM {company_id}.conversations AS c
JOIN LATERAL (
  SELECT *
  FROM {company_id}.messages AS msg
  WHERE msg.conversation_id = c.conversation_id
  ORDER BY msg.created_at DESC, msg.message_id DESC
  LIMIT 1
) AS m ON true
WHERE m.sender_type = 'customer';
"""