"""
Alembic helper functions for managing company-specific schemas.
This module provides utilities to create and manage company schemas using Alembic migrations.
"""
from sqlalchemy import text, inspect
from db.db_connection import engine
import logging

logger = logging.getLogger(__name__)


def create_company_schema_with_tables(company_schema_name: str):
    """
    Create a company-specific schema and all required tables using Alembic operations.
    
    Args:
        company_schema_name: The schema name for the company (e.g., 'company_1234567890')
    
    Returns:
        dict: Status dictionary with 'status' and 'message' keys
    """
    try:
        logger.info(f"Creating schema and tables for: {company_schema_name}")
        
        # Use a connection from the engine
        with engine.begin() as connection:
            # Create schema
            connection.execute(text(f"CREATE SCHEMA IF NOT EXISTS {company_schema_name}"))
            logger.info(f"✅ Schema created: {company_schema_name}")
            
            # Create customers table
            connection.execute(text(f"""
                CREATE TABLE IF NOT EXISTS {company_schema_name}.customers (
                    customer_id uuid NOT NULL DEFAULT gen_random_uuid(),
                    customer_name text NULL,
                    customer_email text NULL,
                    customer_phone text NULL,
                    created_at timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT customers_pkey PRIMARY KEY (customer_id)
                )
            """))
            
            logger.info(f"✅ Created customers table in {company_schema_name}")
            
            # Create conversations table
            connection.execute(text(f"""
                CREATE TABLE IF NOT EXISTS {company_schema_name}.conversations (
                    conversation_id uuid NOT NULL DEFAULT gen_random_uuid(),
                    conversation_name text NOT NULL,
                    ai_reply boolean NOT NULL DEFAULT true,
                    created_at timestamp without time zone NOT NULL DEFAULT now(),
                    updated_at timestamp without time zone NULL DEFAULT now(),
                    source text NOT NULL,
                    phone_number text NULL,
                    instance_name text NULL,
                    customer_id uuid NULL,
                    agent_id uuid NULL,
                    CONSTRAINT conversations_pkey PRIMARY KEY (conversation_id),
                    CONSTRAINT conversations_customer_id_fkey FOREIGN KEY (customer_id) 
                        REFERENCES {company_schema_name}.customers (customer_id),
                    CONSTRAINT conversations_agent_id_fkey FOREIGN KEY (agent_id) 
                        REFERENCES public.users (id)
                )
            """))
            logger.info(f"✅ Created conversations table in {company_schema_name}")
            
            # Create messages table
            connection.execute(text(f"""
                CREATE TABLE IF NOT EXISTS {company_schema_name}.messages (
                    message_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    conversation_id uuid NOT NULL,
                    sender_type text NOT NULL,
                    sender_email text NULL,
                    content text NULL,
                    created_at timestamp without time zone NULL DEFAULT CURRENT_TIMESTAMP,
                    extra json NULL,
                    energy double precision NULL,
                    carbon double precision NULL,
                    CONSTRAINT messages_pkey PRIMARY KEY (message_id),
                    CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) 
                        REFERENCES {company_schema_name}.conversations (conversation_id),
                    CONSTRAINT messages_sender_type_check CHECK (
                        sender_type = ANY (ARRAY['customer'::text, 'bot'::text, 'agent'::text])
                    )
                )
            """))
            logger.info(f"✅ Created messages table in {company_schema_name}")
            
            # Create images table
            connection.execute(text(f"""
                CREATE TABLE IF NOT EXISTS {company_schema_name}.images (
                    id uuid NOT NULL DEFAULT gen_random_uuid(),
                    file_name text NOT NULL,
                    file_type text NOT NULL,
                    file_hash text NOT NULL,
                    full_path text NOT NULL,
                    status text NOT NULL,
                    extra json NULL,
                    match_field text NOT NULL,
                    created_at timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT images_pkey PRIMARY KEY (id)
                )
            """))
            logger.info(f"✅ Created images table in {company_schema_name}")
            
            # Create documents table
            connection.execute(text(f"""
                CREATE TABLE IF NOT EXISTS {company_schema_name}.documents (
                    id uuid NOT NULL DEFAULT gen_random_uuid(),
                    file_name text NOT NULL,
                    file_type text NOT NULL,
                    file_hash text NOT NULL,
                    full_path text NOT NULL,
                    status text NOT NULL,
                    extra json NULL,
                    match_field text NOT NULL,
                    created_at timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT documents_pkey PRIMARY KEY (id)
                )
            """))
            logger.info(f"✅ Created documents table in {company_schema_name}")
            
            # Create knowledges table
            connection.execute(text(f"""
                CREATE TABLE IF NOT EXISTS {company_schema_name}.knowledges (
                    id uuid NOT NULL DEFAULT gen_random_uuid(),
                    file_name text NOT NULL,
                    file_type text NOT NULL,
                    file_hash text NOT NULL,
                    full_path text NOT NULL,
                    status text NOT NULL,
                    primary_column text NOT NULL,
                    extra json NULL,
                    created_at timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT knowledges_pkey PRIMARY KEY (id)
                )
            """))
            logger.info(f"✅ Created knowledges table in {company_schema_name}")
            
            # Create workflows table
            connection.execute(text(f"""
                CREATE TABLE IF NOT EXISTS {company_schema_name}.workflows (
                    id uuid NOT NULL DEFAULT gen_random_uuid(),
                    name text NOT NULL,
                    nodes json NOT NULL,
                    edges json NOT NULL,
                    status text NOT NULL,
                    enable_workflow boolean NOT NULL,
                    except_case text NOT NULL,
                    extra json NULL,
                    created_at timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT workflows_pkey PRIMARY KEY (id)
                )
            """))
            logger.info(f"✅ Created workflows table in {company_schema_name}")

        logger.info(f"✅ Successfully created all tables for {company_schema_name}")
        return {"status": "success", "message": f"Company schema {company_schema_name} created successfully"}

    except Exception as e:
        logger.error(f"❌ Error creating company schema {company_schema_name}: {e}")
        return {"status": "error", "message": str(e)}


def check_company_schema_exists(company_schema_name: str) -> bool:
    """
    Check if a company schema exists in the database.

    Args:
        company_schema_name: The schema name to check

    Returns:
        bool: True if schema exists, False otherwise
    """
    try:
        inspector = inspect(engine)
        schemas = inspector.get_schema_names()
        return company_schema_name in schemas
    except Exception as e:
        logger.error(f"Error checking schema existence: {e}")
        return False


def drop_company_schema(company_schema_name: str, cascade: bool = True):
    """
    Drop a company schema and all its tables.

    Args:
        company_schema_name: The schema name to drop
        cascade: If True, drop all objects in the schema (default: True)

    Returns:
        dict: Status dictionary with 'status' and 'message' keys
    """
    try:
        logger.info(f"Dropping schema: {company_schema_name}")

        with engine.begin() as connection:
            cascade_clause = "CASCADE" if cascade else "RESTRICT"
            connection.execute(text(f"DROP SCHEMA IF EXISTS {company_schema_name} {cascade_clause}"))

        logger.info(f"✅ Successfully dropped schema: {company_schema_name}")
        return {"status": "success", "message": f"Schema {company_schema_name} dropped successfully"}

    except Exception as e:
        logger.error(f"❌ Error dropping schema {company_schema_name}: {e}")
        return {"status": "error", "message": str(e)}

